services:
  elasticsearch:
    image: elasticsearch:7.14.0
    container_name: local-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - dev-network

  kibana:
    image: kibana:7.14.0
    container_name: local-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - dev-network

volumes:
  elasticsearch-data:

networks:
  dev-network: