version: '3'

services:
  mongodb:
    image: mongo:4.4
    container_name: local-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb123
    volumes:
      - mongodb-data:/data/db
    networks:
      - dev-network

volumes:
  mongodb-data:
    name: mongodb-data
    driver: local

networks:
  dev-network:
    name: dev-network
    driver: bridge
    external: true